version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  mmongo:
    image: mongo
    container_name: mmongo
    ports:
      - 25000:27017
  smongo:
    image: mongo
    container_name: smongo
    ports:
      - 26000:27017
  master:
    image: master:latest
    container_name: master
    restart: on-failure
    build: ./Master
    command: "npm start"
    environment:
      - WORKER=MASTER
      - DB_CONNECTION=mongodb://mmongo:27017
      - RMQ_ADDR=amqp://localhost
    depends_on:
      - mmongo