version: "1"
services:
  orchestrator:
    container_name: orchestrator
    image: orchestrator:latest
    restart: always
    build: ./Orchestrator
    command: npm start
    ports: 
      - 80:80
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    
  